# Dockerfile.base
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends iproute2 && rm -rf /var/lib/apt/lists/*

COPY server/requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt